config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # nest the attendings routes under events to allow you to pass @event in the url to controller
  resources :events do
    post 'create_invite', to: 'invites#create'
    delete 'destroy_invite', to: 'invites#destroy'
  end

  # nesting the attendings routes under event passed the event_id to controller in addition to the
  # manually entered hash values for event and user, which causes an error. Could resolve this?
  post 'create_attending', to: 'attendings#create'
  delete 'destroy_attending', to: 'attendings#destroy'

  # sets url /my_events to show user's events
  get 'my_events', to: 'users#show'

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attending.rb
class Attending < ApplicationRecord

  scope :confirmed, ->(event_id) { where(attended_event_id: event_id) }

  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'

  validates_presence_of :attendee_id, :attended_event_id
end

app/models/event.rb
class Event < ApplicationRecord
  # scope allows common queries to be defined herein and method names set
  scope :past_events, -> { where('date < ?', Time.zone.now) }
  scope :future_events, -> { where('date > ?', DateTime.now.strftime) }

  has_many :invites, dependent: :destroy
  has_many :attendings, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :attendings, dependent: :destroy
  belongs_to :creator, class_name: "User"

  validates :name, :location, :date, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates_presence_of :creator_id

end

app/models/invite.rb
class Invite < ApplicationRecord

  scope :received, ->(event_id, user_id) { where(event_id: event_id, invitee_id: user_id) }

  belongs_to :event
  belongs_to :inviter, class_name: 'User'
  belongs_to :invitee, class_name: 'User'

  validates_presence_of :event_id, :inviter_id, :invitee_id

end

app/models/user.rb
class User < ApplicationRecord
  scope :attending_event, ->(event_id) { self.attendings.where(attended_event_id: event_id).exists? }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :invites, foreign_key: :inviter_id, dependent: :destroy
  has_many :invites, foreign_key: :invitee_id, dependent: :destroy
  has_many :attendings, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendings, dependent: :destroy
  # associates user_id with creator_id in events table and allows event.creator method
  has_many :events, foreign_key: :creator_id, class_name: "Event", dependent: :destroy


  def username
    email.split('@')[0].capitalize
  end
  def current_user
    email.split('@')[0].capitalize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendings_controller.rb
class AttendingsController < ApplicationController

  before_action :authenticate_user!

  # check the attending does not already exist
  def create
    if Attending.find_by(attending_params).nil?
      @attending = Attending.new(attending_params)

      respond_to do |format|
        if @attending.save
          format.html { redirect_to my_events_path, notice: "You are attending this event!" }
        else
          format.html { redirect_to my_events_path, alert: "An error occured." }
        end
      end
    else
      flash.alert = 'You are already attending.'
      redirect_to my_events_path
    end
  end

  # to prevent errors, check if record exists
  # check destroy worked and notify
  def destroy
    @attending = Attending.find_by(attending_params)
    if @attending.nil?
      flash.alert = "This event attendance does not exist"
    elsif @attending.destroy
      flash.notice = "You are no longer attending this event."
    else
      flash.alert = "Error - attendance was not deleted."
    end
    redirect_to my_events_path
  end
  
  private

  def attending_params
    params.permit(:attendee_id, :attended_event_id)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]
  # authorizing access to the events resource - only creator can access
  before_action :authorize_item, only: [:update, :edit, :destroy]

  def index
    @events = Event.all.order('created_at DESC')
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find_by(id:params[:id])
  end

  def update
    @event = Event.find_by(params[:id])
    if @event.nil?
      flash.alert = 'Event does not exist'
    elsif @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # check destroy worked and notify
  def destroy
    @event = Event.find_by(params[:id])
    if @event.nil?
      flash.alert = 'Event does not exist'
    elsif @event.destroy
      flash.notice = 'Event was deleted.'
    else
      flash.alert = 'Error - event was not deleted.'
    end
    redirect_to root_path, status: :see_other
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :description, :location, :date, :private)
  end

  def authorize_item
    unless @event.creator == current_user
      redirect_to @event, alert: 'You are not authorized do that.'
    end
  end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!

  def create
    @invite = Invite.new(invite_params)

    respond_to do |format|
      if @invite.save
        format.html { redirect_to event_path(invite_params[:event_id]), notice: "Invite sent!" }
      else
        format.html { redirect_to root_path, status: :unprocessable_entity }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # to prevent errors, check if record exists
  # check destroy worked and notify
  def destroy
    @invite = Invite.find_by(invite_params)
    if @invite.nil?
      flash.alert = "This invite does not exist"
    elsif @invite.destroy
      flash.notice = "Invite Denied."
    else
      flash.alert = "Error - invite was not deleted."
    end
    redirect_to my_events_path
  end
  
  private

  def invite_params
    # no require method here because I am not using an invite#new object above
    params.permit(:event_id, :invitee_id, :inviter_id)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private

  def sign_up_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @created_events = current_user.events.all
    @attended_events = current_user.attended_events.past_events
    @attending_events = current_user.attended_events.future_events
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attendeelist.html.erb
 <div class="wrapper">
    <h1>List of Attendees</h1>
    <% @event.attendees.each do | attendee |%>
    <p class="attendee__name"><%= attendee.username %> </p>
    <% end %>
</div>

app/views/events/_form.html.erb
<div class="form__event">
  <%= simple_form_for(@event) do | f | %>
    <%= f.error_notification %>
          <div class="form__inputs">
            <div class="field">
            <%= f.input :name,
                        label: 'Event Name',
                        input_html: { class: 'input' },
                        wrapper: false, label_html: { class: 'label' },
                        required: true,
                        autofocus: true %>
              </div>

              <div class="field">
            <%= f.input :location,
                        label: 'Event Location',
                        input_html: { class: 'input' },
                        wrapper: false, label_html: { class: 'label' },
                        required: true %>
              </div>
                <div class="field-time">
            <%= f.input :date,
                        label: 'Date & Time',
                        input_html: { class: 'datetime' },
                        wrapper: false, label_html: { class: 'label' },
                        required: true %>
              </div>

                <div class="field-desc">
            <%= f.input :description,
                        label: 'Event Description',
                        input_html: { class: 'textarea' },
                        wrapper: false, label_html: { class: 'label' },
                        placeholder: 'The desctiption of your event...' %>
            </div>
              <div class="field">
             <%= f.input :private,
                        label: 'Private Event',
                        input_html: { class: 'checkbox' },
                        wrapper: false, label_html: { class: 'label' } %>
              </div>
        </div>
      <div class="form__actions">
        <%= f.button :submit%>
        <%= link_to "Cancel", events_path,class:"cancel" %>
    </div>

  <% end %>

</div>

app/views/events/_invitepane.html.erb
<div class="sendInvites__container">
  <p class="title">User List</p>
          <% User.all.order('email Asc').each do | user |%>
            <% unless user.id == current_user.id %>
              <div class="box invites">
                  <p><strong><%= user.username %></strong></p>
                  <% if user.attendings.confirmed(@event.id).exists? %>
                    <div>
                      <p class="status">Status: User attending</p>
                    </div>
                  <% elsif %>
                    <% user.invites.received(@event.id, user.id).exists? %>
                      <%= link_to 'Cancel Invitation', event_destroy_invite_path(:event_id=> @event.id, :invitee_id=> user.id),
                          data: { turbo_method: "delete" }, class: 'button ' %>
                      <div>
                        <p  class="status">Status: Invitation Sent</p>
                      </div>
                  <% else %>
                      <%= link_to 'Invite', event_create_invite_path(:event_id => @event.id, :invitee_id=> user.id, :inviter_id=> current_user.id),
                          data: { turbo_method: "post" }, class: 'button' %>
                  <% end %>
              </div>
            <% end %>
          <% end %>
  </div>

app/views/events/_past.html.erb
<h3 class="title">Past Events</h3>
    <div class="card__container">
        <% @events.past_events.each do | event |%>
                <div class="event__card">
                    <p><%= link_to event.name, event, class:"event__title"%></p>
                    <p><%= event.date.strftime("%B")[0,3] %> &nbsp;</p>
                    <p><%= event.date.year %> &nbsp; &nbsp;</p>
                    <p><%= link_to 'Read more', event, class: 'button' %> &nbsp; &nbsp;</p>
                </div>
        <% end %>
    </div>

app/views/events/_upcoming.html.erb
<h1 class="title">Upcoming Events</h1>
       <div class="card__container">

        <% @events.future_events.each do | event |%>
          <div class="event__card" <%= ' Current User' if event.creator == current_user %> >
                <p class="event__title"><%=event.creator.username%> - <%= event.name %>  </p>

                    <% if event.private == true %>
                        <p><strong>Attendance:</strong>&nbsp; invite only</p>
                    <% else %>
                        <p><strong>Attendance:</strong>&nbsp; anyone</p>
                    <% end %>

                    <p><strong>Location:</strong><%= event.location %></p>
                    <p><strong>Date:</strong>

                      <%= event.date.strftime("%B")[0,3] %>
                      <%= event.date.strftime("%d") %>,
                      <%= event.date.year %></p>
                    <p><%= link_to 'Read more', event, class: 'button' %> &nbsp; &nbsp;</p>
            </div>

  <%#                    <% if user_signed_in? %>

<%#                          <% if event.creator == current_user %>
 <%#                          <p><%= link_to 'Edit', edit_event_path(event), class: 'current__btn' %> <%# &nbsp; &nbsp;</p>
    <%#                       <%= link_to 'Delete', event_path(event),class: 'button', data: { turbo_method: :delete, turbo_confirm: "Click OK to confirm deleting this event." } %>
  <%#                     <% elsif %>
  <%#                         <% event.private == true && current_user.attended_event_ids.include?(event.id) %>
  <%#                           <%= link_to 'Withdraw', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>event.id), data: { turbo_method: "delete", turbo_confirm: "You will need a new invite to attend. Click OK to confirm withdrawing." },class: 'button' %>
   <%#                    <% elsif %>
    <%#                       <% event.private == false && !current_user.attended_event_ids.include?(event.id) %>
    <%#                       <%= link_to 'Attend', create_attending_path(:attendee_id=>current_user.id, :attended_event_id=>event.id), data: { turbo_method: "post" }, class: 'button' %>
    <%#                   <% elsif%>
    <%#                       <% event.private == false %>
  <%#                         <%= link_to 'Withdraw', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>event.id), data: { turbo_method: "delete", turbo_confirm: "Click OK to confirm withdrawing." },class: 'button' %>
  <%#                     <% end %>
 <%#                    <% end %>

                <% end %>
    </div>

app/views/events/edit.html.erb
<div class="form__event">
  <h2 class="title">Edit an Event</h2>
<%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
<div class="events__container">
    <div class="upcoming__events">
        <%= render 'upcoming' %>
    </div>

    <div class="past__events">
    <%= render 'past' %>
    </div>
</div>

app/views/events/new.html.erb
<div class="form__event">
  <h2 class="title">Create an Event</h2>
<%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<div class="show__container">
  <div class="card__container">
            <div class="event__card">
                <h3 class="event__title"><%= @event.name %></h3>
                    <p class="event__host"><strong>Host: </strong><%= @event.creator.username %></strong><br />
                    <p class="event__location"><strong>Location:</strong> <%= @event.location %></p>
                    <p class="event__date"><strong>Date:</strong> <%= @event.date %></p>
                    <p class="event__details"><strong>Details:</strong> <%= @event.description %></p>
                    <% if @event.private == true %>
                      <p  class="event__private"><strong>Attendance:</strong>&nbsp; Private </p>
                    <% else %>
                      <p  class="event__public"><strong>Attendance:</strong>&nbsp; Public</p>
                      <% if user_signed_in? %>

                      <% else %>
                          <%= link_to 'Sign in to attend', new_user_session_path, class: 'button' %>
                      <% end %>
                    <% end %>

                      <% if user_signed_in? %>
                        <% if @event.creator == current_user %>
                         <div class="button__container">
                          <%= link_to 'Edit', edit_event_path(@event), class: 'btn' %> &nbsp; &nbsp;</p>
                          <%= link_to 'Delete', event_path(@event),
                              class: 'btn',
                              data: { turbo_method: :delete,
                                      turbo_confirm: "Click OK to confirm deleting this event." } %>
                          </div>
                       <% elsif %>
                          <% @event.private == true && current_user.attended_event_ids.include?(@event.id) %>
                            <%= link_to 'Cancell', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>@event.id),
                                data: { turbo_method: "delete",
                                        turbo_confirm: "You will need a new invite to attend. Click OK to confirm withdrawing." },
                                        class: 'button' %>
                        <% elsif %>
                          <% @event.private == false && !current_user.attended_event_ids.include?(@event.id) %>
                          <%= link_to 'Attend', create_attending_path(:attendee_id=>current_user.id, :attended_event_id=>@event.id),
                                    data: { turbo_method: "post" }, class: 'button' %>
                        <% elsif%>
                          <% @event.private == false %>
                          <%= link_to 'Cancel', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>@event.id),
                                data: { turbo_method: "delete",
                                        turbo_confirm: "Are you sure you don't want to attend?." },
                                        class: 'button' %>
                        <% end %>
                        <% else %>
                      <% end %>
                 </div>

    </div>
    <div class="attendee__container">
      <%= render 'attendeelist' %>
      <% if @event.creator == current_user %>
              <%= render 'invitepane' %>
      <% end %>
      <div>
</div>

app/views/layouts/_alerts.html.erb
<% if notice%>
    <p class="notice alert-success" role="alert"><%= notice %></p>
    <% elsif alert%>
    <p class="alert alert-danger" role="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="nav-container">
    <div class="nav-brand">
        <%= link_to root_path do %>
        <%= image_tag "bootyard.png", class: "navbar-image" %>
        <% end %>
        <h1 class="title"> BOOT
        <span>
            <%= link_to "YARD", root_path, style: "color: #db0303; text-decoration: none "%>        </span , root_path></h1>
        <%# link all posts  %>
        
            <h2><%= link_to "Events", events_path%></h2>
    
    </div>

   
   
    <div class="btn-wrapper">
                  
                <%= link_to "HOME", root_path,class:"home_event" %>
                 <%= link_to "NEW ", new_event_path,class:"new_event" %>
                <%= link_to "Create Event", new_event_url , class:"home_event" %></li>
                       <%= link_to "My Events", my_events_url, class:"new_event" %></li>

                </div>
    <div class="nav-dropdown">
    
        <div class="button-container"data-bs-theme="dark">
            <%if current_user %>
                <div class="dropdown">
                <a class="btn btn-danger dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= current_user.email.split('@')[0].capitalize %>
                </a>
                    <ul class="dropdown-menu " aria-labelledby="dropdownMenuButtonDark">
                        
                        <li class="d-flex justify-content-center first"><%= link_to "My Account", edit_user_registration_path, class:"link" %></li>
                        <li class="d-flex justify-content-center first"><%= button_to "Log out", destroy_user_session_path, method: :delete,  class:"link" %></li>
                    </ul>
                </div>
        </div>
            <%else%>
                <div class="btn-wrapper">
                  
                <%= link_to "HOME", root_path,class:"home_event" %>
                 <%= link_to "NEW ", new_event_path,class:"new_event" %>
                <%= link_to "Sign Up", new_user_registration_path, class:"sign__up"%>
                <%= link_to "Sign In", new_user_session_path, class:"sign__in"%>

                </div>
            <%end%>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>

  </head>

  <body>
  <header>
  <%= render "layouts/navbar"%>
 </header>
  <main>
    <%= render "layouts/alerts" %>
    <%= yield %>
    </main>
  </body>
</html>

app/views/users/_attended.html.erb
<div class="my__events">
  <h3 class= "title">My Past Events</h3>
      <div class="card__container">
        <% @attended_events.each do | event |%>
          <div class="event__card">
            <p class="event__title"><%= event.name %></p>
            <p class="event__host"><strong>Host:</strong><%= event.creator.username %></strong><br/></p>
              <p class="event__location"><strong>Location:</strong> <%= event.location %></p>
              <p class="event__date"><strong>Date:</strong>
                <%= event.date.strftime("%B")[0,3] %>
                <%= event.date.strftime("%d") %>,
                <%= event.date.year %></p>
                <div class="button__container">
                    <p><%= link_to 'View', event, class: 'btn' %>&nbsp; &nbsp;</p>
                    <p><%= link_to 'Remove', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>event.id),
                                        data: { turbo_method: "delete",
                                                turbo_confirm: "Click OK to confirm withdrawing from this event." },
                                                class: 'btn' %></p>
                  </div>
              </div>
        <% end %>
    </div>
</div>

app/views/users/_attending.html.erb
<div class="my__events">
  <h3 class= "title">My Upcoming Events</h3>
      <div class="card__container">
          <% @attending_events.each do | event |%>
            <div class="event__card" >
              <p class="event__title" ><%= event.name %></p>
              <p class="event__host" ><strong>Host:</strong><%= event.creator.username %></strong><br/></p>
              <p class="event__location" ><strong>Location:</strong> <%= event.location %></p>
              <p class="event__date"><strong>Date:</strong>
              <%= event.date.strftime("%B")[0,3] %>
              <%= event.date.strftime("%d") %>,
              <%= event.date.year %></p>
                <div class="button__container">
                  <p><%= link_to 'View', event, class: 'button' %></p>
                   <P><%= link_to 'Cancel attend', destroy_attending_path(:attendee_id=>current_user.id, :attended_event_id=>event.id),
                              data: { turbo_method: "delete",
                                      turbo_confirm: "Click OK to confirm the cancellation of this this event." },
                                      class: 'button' %></P>
                 </div>
           </div>
        <% end %>
      </div>
</div>

app/views/users/_created.html.erb
<div class="my__events">
  <h3 class="title">My Events</h3>
    <div class="card__container">
            <% @created_events.each do | event |%>
              <div class="event__card">
                <p class="event__host"><strong>Host:</strong><%= event.creator.email %></strong><br/></p>
                <p class="event__location"><strong>Location:</strong> <%= event.location %></p>
                <p class="event__date"><strong>Date:</strong>
                <%= event.date.strftime("%B")[0,3] %>
                <%= event.date.strftime("%d") %>,
                <%= event.date.year %></p>
                <div class="button__container">
                  <p><%= link_to 'View', event, class: 'btn' %></p>
                  <p><%= link_to 'Edit', edit_event_path(event), class: 'btn' %>&nbsp; &nbsp;</p>
                </div>
                <p><%= link_to 'Cancel Event', event_path(event), class: 'button', data: { turbo_method: :delete, turbo_confirm: "Click OK to confirm cancelling this event."} %></p>
          </div>
        <% end %>
    </div>
</div>

app/views/users/_invites.html.erb
    <div class="invitation__container">
        <h4 class= "title" > Someone Invitate you!</h4>
                <% current_user.invites.each do | invite |%>
                    <div class="event__card">
                        <h3 class ="event__title__invite"><%= invite.event.name %>&nbsp;</h3>
                        <div class="button__container">
                            <%= link_to 'View', event_path(invite.event_id), class: 'btn' %>
                            <%if !current_user.attended_event_ids.include?(invite.event_id) %>
                                <%= link_to 'Accept', create_attending_path(:attendee_id=>current_user.id, :attended_event_id=>invite.event_id),
                                    data: { turbo_method: "post" }, class: 'btn' %>
                            <% end %>
                                <%= link_to 'Decline', event_destroy_invite_path(:event_id=> invite.event_id, :invitee_id=> current_user.id),
                                            data: { turbo_method: "delete" }, class: 'btn' %><br />
                        </div>
                    </div>
            <% end %>
 </div>

app/views/users/show.html.erb
<div class="user__container">
<% if current_user.invites.exists? %>
        <%= render 'invites' %>
<% end %>
    <%= render 'created' %>
    <%= render 'attending' %>
    <%= render 'attended' %>
</div>